# Generated by Django 5.0.6 on 2024-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='est_date',
        ),
        migrations.AddField(
            model_name='company',
            name='estd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
