# Generated by Django 5.0.6 on 2024-05-16 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 16, 16, 43, 24, 386106, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
