# Generated by Django 5.0.6 on 2024-05-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_industry_state_job_job_type_job_industry_job_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='city',
        ),
    ]
